// <auto-generated />
using System;
using APIServer.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIServer.Migrations
{
    [DbContext(typeof(WithusContext))]
    [Migration("20230912231416_table_user_info2")]
    partial class table_user_info2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("APIServer.Entitys.Tb_User_Info", b =>
                {
                    b.Property<int>("uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("advisor")
                        .HasMaxLength(25)
                        .HasColumnType("VARCHAR")
                        .HasColumnOrder(7);

                    b.Property<DateTime>("created_datetime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnOrder(9);

                    b.Property<bool>("is_activity")
                        .HasColumnType("TINYINT(1)")
                        .HasColumnOrder(8);

                    b.Property<string>("recommender")
                        .HasMaxLength(25)
                        .HasColumnType("VARCHAR")
                        .HasColumnOrder(6);

                    b.Property<DateTime>("updated_datetime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TIMESTAMP")
                        .HasColumnOrder(10);

                    b.Property<string>("user_email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("VARCHAR")
                        .HasColumnOrder(2);

                    b.Property<string>("user_name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR")
                        .HasColumnOrder(4);

                    b.Property<string>("user_password")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("VARCHAR")
                        .HasColumnOrder(3);

                    b.Property<string>("user_phone")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("VARCHAR")
                        .HasColumnOrder(5);

                    b.HasKey("uid");

                    b.HasIndex("user_email")
                        .IsUnique();

                    b.HasIndex("user_phone")
                        .IsUnique();

                    b.ToTable("tb_user_info");
                });
#pragma warning restore 612, 618
        }
    }
}
